# Generated by Django 5.0 on 2023-12-17 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderId', models.CharField(primary_key=True, serialize=False)),
                ('totalPrice', models.IntegerField()),
                ('items', models.JSONField()),
                ('date', models.DateTimeField()),
                ('confirmed', models.BooleanField()),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
